#use_frameworks!

platform :ios, '9.0'

target 'PHPayLib_Example' do
  pod 'PHPayLib', :path => '../'
  pod 'PHPayLib/Core', :path => '../'
  pod 'PHPayLib/WeChatPay', :path => '../'
  pod 'PHPayLib/AliPay', :path => '../'
  #pod 'PHPayLib/UnionPay', :path => '../'
  pod 'PHPayLib/ApplePay', :path => '../'
  pod 'PHPayLib/IapPay', :path => '../'

  target 'PHPayLib_Tests' do
    inherit! :search_paths
    
  end
end
